# Generated by Django 5.2.3 on 2025-06-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('HSN', models.CharField(max_length=20, unique=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
